version: '3.8'

services:
  db:
    restart: always
    env_file:
      - docker-compose.env
    ports:
      - "5432:5432"
    image: postgres:17.6-alpine

  vm:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.124.0
    ports:
      - "8428:8428"
    restart: always

  producer:
    depends_on:
      - db
    env_file:
      - docker-compose.env
    build:
      context: .
    entrypoint: [ "/go/bin/producer", "-wait", "10", "-truncate" ]

  worker:
    depends_on:
      - db
      - vm
    env_file:
      - docker-compose.env
    build:
      context: .
    entrypoint: [ "/go/bin/swapper-worker", "-wait", "10"]

  api:
    depends_on:
      - vm
    build:
      context: .
    ports:
      - "8085:8085"
    entrypoint: [ "/go/bin/swapper-api", "-http-addr", "0.0.0.0", "-http-port", "8085"]
